export * from "./interfaces/themeStore.interface";
export * from "./interfaces/colorsTheme.interface";
export * from "./interfaces/IAuthenticationStore";
export * from "./interfaces/IToken";
export * from "./interfaces/INavStore";
export * from "./interfaces/ISideNav.items";
export * from "./interfaces/ICredentials";
export * from "./interfaces/ICredentialsToken";
export * from "./interfaces/IPagination";
export * from "./interfaces/IAddress";
export * from "./interfaces/ICustomers";
export * from "./interfaces/IPhoneBook";
export * from "./interfaces/IAppliance";
export * from "./interfaces/IBrands";
export * from "./interfaces/IUsers";
//      export * from "";
