export const enum LABELS {
  HOME = "Inicio",
  TITLE = "Servistar",
  CUSTOMERS = "Clientes",
  CUSTOMER = "Cliente",
  SERVICES = "Servicios",
  SERVICE = "Servicio",
  NAME = "Nombre",
  LAST_NAME = "Primer Apellido",
  SECOND_LAST_NAME = "Segundo Apellido",
  BIRTH_DATE = "Fecha nacimiento",
  UPLOAD = "Subir",
  ADD = "Agregar",
  DELETE = "Eliminar",
  CANCEL = "Cancelar",
  LOG_IN = "Acceder",
  LOG_OUT = "Cerrar sesión",
  ACTIVATE = "Activar",
  DEACTIVATE = "Desactivar",
}
